Repository hellohaptik/unleash-client-python, pull requests merged in 2022-06, with the labels that each got.

#34 LRU cache added for feature toggles
  FeatureToggle/__init__.py
  FeatureToggle/utils.py
Labels: miscellaneous

#36 Remove unwanted imports
  FeatureToggle/__init__.py
Labels: miscellaneous

#35 develop -> master
  FeatureToggle/__init__.py
  FeatureToggle/utils.py
Labels: miscellaneous

#39 cache info logger added
  FeatureToggle/__init__.py
  FeatureToggle/utils.py
  UnleashClient/utils.py
Labels: miscellaneous

#40 Develop-> master release
  FeatureToggle/__init__.py
  FeatureToggle/utils.py
  UnleashClient/utils.py
Labels: miscellaneous

#42 Check if data was properly saved in redis
  FeatureToggle/__init__.py
Labels: enhancement

#41 Return empty response from Feature Toggles Library if redis is down
  FeatureToggle/__init__.py
Labels: bug, enhancement

#43 Develop to Master
  FeatureToggle/__init__.py
Labels: miscellaneous
